document.writeln("<header class=\'layout-header mdl-layout__header mdl-layout__header--waterfall\'>");
document.writeln("    <div class=\'mdl-layout__header-row\'>");
document.writeln("        <span class=\'layout-title mdl-layout-title\'>");
document.writeln("            <img class=\'logo-image\' src=\'images/slime-logo.png\'>");
document.writeln("        </span>");
document.writeln("        <div class=\'header-spacer mdl-layout-spacer\'></div>");
document.writeln("        <div class=\'navigation-container\'>");
document.writeln("            <nav class=\'navigation mdl-navigation\'>");
document.writeln("                <a class=\'mdl-navigation__link mdl-typography--text-uppercase mainpage\' href=\'index.html\'>首页</a>");
document.writeln("                <a class=\'mdl-navigation__link mdl-typography--text-uppercase introduction\' href=\'introduction.html\'>服务器介绍</a>");
document.writeln("                <a class=\'mdl-navigation__link mdl-typography--text-uppercase members\' href=\'members.html\'>服务器成员</a>");
document.writeln("                <a class=\'mdl-navigation__link mdl-typography--text-uppercase joinus\' href=\'joinus.html\'>加入我们</a>");
document.writeln("            </nav>");
document.writeln("        </div>");
document.writeln("        <span class=\'layout-mobile-title mdl-layout-title\'>");
document.writeln("            <img class=\'logo-image\' src=\'images/slime-logo.png\'>");
document.writeln("        </span>");
document.writeln("    </div>");
document.writeln("</header>");

document.writeln("<div class=\'layout-drawer mdl-layout__drawer\'>");
document.writeln("    <span class=\'mdl-layout-title\'>");
document.writeln("        <img id=\'logo-image-drawer\' class=\'logo-image-drawer\' src=\'images/slime-logo.png\'>");
document.writeln("    </span>");
document.writeln("    <nav class=\'mdl-navigation\'>");
document.writeln("        <a class=\'mdl-navigation__link\' href=\'index.html\'>首页</a>");
document.writeln("        <a class=\'mdl-navigation__link\' href=\'introduction.html\'>服务器介绍</a>");
document.writeln("        <a class=\'mdl-navigation__link\' href=\'members.html\'>服务器成员</a>");
document.writeln("        <div class=\'layout-drawer-separator\'></div>");
document.writeln("        <a class=\'mdl-navigation__link\' href=\'joinus.html\'>加入我们</a>");
document.writeln("    </nav>");
document.writeln("</div>");